sqs:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
  ports:
    - "9324:9324"
    - "4789:9324"
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/zenko/cloudserver:8.1.8"
  environment:
    - "S3BACKEND=mem"
  ports:
    - "33333:8000"
azurite:
  image: "mcr.microsoft.com/azure-storage/azurite"
  ports:
    - "10000:10000"
  command: ["azurite", "--blobHost", "0.0.0.0"]
