version: "3.9"

services:
  aws:
    image: "localstack/localstack"  # TODO: Pin to a specific version
    volumes:
      - "./localstack:/tmp/localstack"

      # Files with extension .sh in this directory will be run when
      # the container is started for the first time.
      # See https://github.com/localstack/localstack#initializing-a-fresh-instance
      - "./init:/docker-entrypoint-initaws.d"
    ports:
      - "4566"
    environment:
      - "SERVICES=dynamodb,iam,s3,sns,sqs"
      - "DEFAULT_REGION=eu-west-1"
      - "HOSTNAME_EXTERNAL=aws"
      - "DATA_DIR=/tmp/localstack/data"

  ingests_tracker:
    image: "ingests_tracker:43c9ad494468929d4a7edb98da7b93f72ac144af"

    restart: "on-failure"

    environment:
      - "aws_key=test"
      - "aws_secret=test"
      - "aws_endpoint=http://aws:4566"
      - "aws_region=eu-west-1"
      - "AWS_REGION=eu-west-1"

      - "ingests_table_name=demo-ingests"
      # - "ingest_tracker_store=memory"
      - "callback_notifications_topic_arn=arn:aws:sns:eu-west-1:000000000000:callback_notifications"
      - "updated_ingests_topic_arn=arn:aws:sns:eu-west-1:000000000000:updated_ingests"
