sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
    - "4789:9324"
s3:
  image: "zenko/cloudserver:8.1.8"
  environment:
    - "S3BACKEND=mem"
  ports:
    - "33333:8000"
azurite:
  image: "mcr.microsoft.com/azure-storage/azurite"
  ports:
    - "10000:10000"
  command: ["azurite", "--blobHost", "0.0.0.0"]
dynamodb:
  image: "peopleperhour/dynamodb"
  ports:
    - "45678:8000"
